#pragma config(Sensor, in1,    Gyro,           sensorGyro)
#pragma config(Sensor, dgtl1,  TL_EN,          sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  TR_EN,          sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  R_EN,           sensorQuadEncoder)
#pragma config(Sensor, dgtl7,  L_EN,           sensorQuadEncoder)
#pragma config(Motor,  port1,           Lift_Left,     tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           Top_Right,     tmotorVex393_MC29, openLoop, reversed, encoderPort, dgtl1)
#pragma config(Motor,  port3,           Top_Left,      tmotorVex393_MC29, openLoop, encoderPort, dgtl3)
#pragma config(Motor,  port4,           Bottom_Right,  tmotorVex269_MC29, openLoop, reversed, encoderPort, dgtl5)
#pragma config(Motor,  port5,           Bottom_Left,   tmotorVex393_MC29, openLoop, encoderPort, dgtl7)
#pragma config(Motor,  port6,           Front_Right,   tmotorVex393_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port7,           Front_Left,    tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port8,           Back_Right,    tmotorVex393_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port9,           Back_Left,     tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port10,          Lift_Right,    tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/* NOTE: All directional names are referring to side of object when viewing robot from the back */


#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(0)
#pragma userControlDuration(60)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!


/////////////////////////////////////////////////////////////////////////////////////////
//
//                         Driver Skills Template
//
// This is a template for the driver skills competition. It is identical in structure to
// the standard competition template except that the two "#pragma' statements above (and
// copied below) adjust the time limits for the competition.
//				#pragma autonomousDuration(0)
//				#pragma userControlDuration(60)
// The autonomous duration for "Driver Skills" is zero; i.e. there is no autonomous phase.
// The user control duration is 60 seconds
//
// NOTE: The above two pragmas only impact the Crystal implementation. For systems using
//       VEXNET, the VEXNET system ignores these statements as it has the durations
//       for the competition built-in.
//
// Whenever this user program is run, the duration is automatically sent to the VEX master
// processor. The master CPU will only accept these commands once per power=on cycle. So, it's
// best to power cycle your VEX to ensure that they get recognized in case you were
// previously running a standard competition program with different durations.
//
// Testing Via VEXNET Using VEXNET Competition Switch
// ==================================================
//
// The procedure to test a Driver Skills program using VEXNET Competition Switch is as follows:
//
// 1. Set the two switches on the Competition switch to "DISABLE" and "USER CONTROL"
//
// 2. Start the Driver skills program
//
// 3. Set Switch to ENABLE from DISABLE
//
// 4. You need to manually time the 60 second duration.
//
// 5. Set Switch to DISABLE
//
// 6. Repeat from step (3) to run subsequent test runs. There's no need to reset the VEX or
//    restart your user program.
//
//
// Testing Via VEXNET Using ROBOTC IDE
// ==================================================
//
// It is not necessary to own a VEXNET switch. ROBOTC has a test window that allows the same functionality.
// The test window has three buttons for "DISABLE", "AUTONOMOUS", "USER CONTROL".
//
// 1. Open the ROBOTC Debugger. Then open the "Competition Control" Debugger window.
//
// 2. Start your Driver Skills program running.
//
// 3. Click the "DISABLED" button on the "Competition Control" window.
//
// 4. Click the "USER CONTROL" button on the "Competition Control" window.
//
// 5. You need to manually time the 60 second duration.
//
// 6. Click the "DISABLED" button on the "Competition Control" window.
//
// 7. Repeat from step (4) to run subsequent test runs. There's no need to reset the VEX or
//    restart your user program.
//
/////////////////////////////////////////////////////////////////////////////////////////

// Variables
int height = 360; // Top lift encoder limit
int ground = 5;	// Bottom lift encoder limit

//******************************************** Driver Control Tasks ************************************************//
task d_drive()
{
	while(true)
	{
		motor[Back_Left]  = (vexRT[Ch4] + vexRT[Ch3])/2;
		motor[Front_Left]  = (vexRT[Ch4] + vexRT[Ch3])/2;
		motor[Back_Right] = (vexRT[Ch2] + vexRT[Ch1])/2;
		motor[Front_Right]  = (vexRT[Ch2] + vexRT[Ch1])/2;
	}
}

task d_lift() // Driver lift control
{
	while(true)
	{
		while((vexRT[Btn6U] == 1) && (abs(SensorValue[TR_EN]) < abs(height))) // While Button 6U is pressed and lift is within hight limit, raise lift
		{
			motor[Top_Right] = 110;
			motor[Bottom_Right] = 110;
			motor[Top_Left] = 110;
			motor[Bottom_Left] = 110;
		}
		if(abs(SensorValue[TR_EN]) >= abs(height)) // If Button 6U is pressed but lift is not within hight limit, stop
		{
			motor[Top_Left] = 0;
			motor[Top_Right] = 0;
			motor[Bottom_Left] = 0;
			motor[Bottom_Right] = 0;
		}

		while((vexRT[Btn6D] == 1) && (abs(SensorValue[TR_EN]) > abs(ground))) // While Button 6D is pressed and lift is above ground limit, lower lift
		{
			motor[Top_Right] = -90;
			motor[Bottom_Right] = -90;
			motor[Top_Left] = -90;
			motor[Bottom_Left] = -90;
		}
		if(abs(SensorValue[TR_EN]) <= abs(ground)) // If Button 6D is pressed but lift is not above ground limit, stop
		{
			motor[Top_Left] = 0;
			motor[Top_Right] = 0;
			motor[Bottom_Left] = 0;
			motor[Bottom_Right] = 0;
		}

		else // If neither button pressed, stop
		{
			motor[Top_Left] = 0;
			motor[Top_Right] = 0;
			motor[Bottom_Left] = 0;
			motor[Bottom_Right] = 0;
		}
	}
}

task d_popper() // Driver popper control
{
	while(true)
	{
		motor[Lift_Left] = 0;
		motor[Lift_Right] = 0;

		while(vexRT[Btn5U] == 1) // Popper activated while Button 5U held down
		{
			motor[Lift_Left] = 127;
			motor[Lift_Right] = 127;
		}

		while(vexRT[Btn5D] == 1) // Popper deactivated while Button 5D held down
		{
			motor[Lift_Left] = -100;
			motor[Lift_Right] = -100;
		}
	}
}

//************************************************** PRE-AUTONOMOUS *******************************************//
void pre_auton()
{
	bStopTasksBetweenModes = true;
}

//************************************************** AUTONOMOUS ***********************************************//
task autonomous()
{
	AutonomousCodePlaceholderForTesting();
}

//************************************************ USER CONTROL *******************************************//
task usercontrol()
{
	// Reset Encoders
	SensorValue[R_EN] = 0;
	SensorValue[L_EN] = 0;
	SensorValue[TR_EN] = 0;
	SensorValue[TL_EN] = 0;

	while (true)
	{
		// Start drive, popper, and lift tasks and run them simulatneously
		startTask(d_drive);
		startTask(d_lift);
		startTask(d_popper);

		while(true)
		{
			wait1Msec(1); // Keep the program alive; DO NOT DELETE
		}
	}
}
