#pragma config(Sensor, in1,    Gyro,           sensorGyro)
#pragma config(Sensor, dgtl1,  TL_EN,          sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  TR_EN,          sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  R_EN,           sensorQuadEncoder)
#pragma config(Sensor, dgtl7,  L_EN,           sensorQuadEncoder)
#pragma config(Motor,  port1,           Lift_Left,     tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           Top_Right,     tmotorVex393_MC29, openLoop, reversed, encoderPort, dgtl1)
#pragma config(Motor,  port3,           Top_Left,      tmotorVex393_MC29, openLoop, encoderPort, dgtl3)
#pragma config(Motor,  port4,           Bottom_Right,  tmotorVex269_MC29, openLoop, reversed, encoderPort, dgtl5)
#pragma config(Motor,  port5,           Bottom_Left,   tmotorVex393_MC29, openLoop, encoderPort, dgtl7)
#pragma config(Motor,  port6,           Front_Right,   tmotorVex393_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port7,           Front_Left,    tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port8,           Back_Right,    tmotorVex393_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port9,           Back_Left,     tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port10,          Lift_Right,    tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/* NOTE: All directional names are referring to side of object when viewing robot from the back */
